- name: backend configurations for expense project
  hosts: Backend
  become: true
  tasks:
  - name: disabling nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enabling version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: installing nodejs and mysql
    ansible.builtin.dnf:
      name : "{{ item }}"
      state: installed
    loop:
      - nodejs
      - mysql
  - name: assing user
    ansible.builtin.user:
      name: expense
      state: present
  - name: create directory when not present
    ansible.builtin.command: mkdir /app
    when: changed is true
  - name: Dowloading application code to tmp directory
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: Unzip the file that is tmp directory
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /tmp/
      remote_src: yes