- name: Condfiguring DB 
  hosts: DB
  become: true
  vars:
    login_host: db.itindustry.online
  vars_prompt:
  - name: mysql-root-password
    prompt: please enter password
    private: no
  tasks:
    - name: installing mysql server
      ansible.builtin.dnf:
        name: mysql
        state: latest
    - name: enabling mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: check DB connection
      community.mysql.mysql_info:
        login_user: "{{ login_host }}"
        login_password: "{{ mysql-root-password }}"
        filter: version
      ignore_errors: yes
      register: connection_output
    - name: printing output of the connection with password
      ansible.builtin.debug:
        msg: Output of connection is {{ connection_output }}
    - name: Setting up the password
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
      when: connection_output.failed is true