- name: Condfiguring DB 
  hosts: DB
  become: true
  tasks:
    - name: installing mysql server
      ansible.builtin.command: dnf install mysql-server -y
    - name: enabling mysql service
      service:
        name: mysqld
        enabled: yes

