- name: Condfiguring DB 
  hosts: DB
  become: true
  tasks:
    - name: installing mysql server
      ansible.builtin.dnf:
        name: mysql
        state: latest
    - name: enabling mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes



