- name: configuration fro frontend service
  hosts: Frontend
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      - name: nginx
        state: latest
  - name: start and enable nginx
    ansible.builtin.service:
      - name: nginx
        state: started
        enabled: yes
  - name: Delete html directory which is default
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html
  - name: creating html directory again to download frontend code
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html